### PR TITLE
Update Terraform to smaller instance with more secure/updated configuration

### PR DESCRIPTION
**Pull request by neuroretransmit**
* Updated to Ubuntu 20.04
* Using nano instance instead of micro
* More secure configurations
* Extended configurations for unbound
* In addition this also generates a client for both your router (or PC) and phone.

### CODE REVIEW

**Comment by castironclay** [comment]
LGTM

**Comment by castironclay** [comment]
Thanks @optimisticninja !

**Comment by neuroretransmit** [comment]
> Thanks @optimisticninja !

No problem! Did you ever figure out the EOT issue for the keys/configs? This was honestly my first Terraform project.

**Comment by castironclay** [comment]
No I have not. I have not gotten back around to this project for a little while. Been doing a lot more Docker stuff. Shouldn't be too difficult to remove those. I did have a successful deployment yesterday with your changes. Just had to ignore those EOT lines. Still a useful project

**Comment by neuroretransmit** [comment]
Most definitely. Cheers m8. Don't forget to tag a release!

**Pull request merged**
